apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hn-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - hn.qpoint.io
    secretName: hn-tls
  defaultBackend: 
    service:
      name: hn
      port:
        number: 80
  rules:
  - host: hn.qpoint.io
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: hn
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hn
spec:
  selector:
    app: hn
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hn-deployment
  labels:
    app: hn
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hn
  template:
    metadata:
      labels:
        app: hn
    spec:
      containers:
      - name: hn
        image: tylerflint/hacker-news-clone-node:latest
        env:
        ports:
        - containerPort: 3000

      # try to keep them on different nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
            - weight: 1  
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: NotIn 
                    values:
                    - hn
                topologyKey: kubernetes.io/hostname