apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qtap-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - qtap-sandbox.qpoint.io
    secretName: qtap-tls
  defaultBackend: 
    service:
      name: qtap
      port:
        number: 80
  rules:
  - host: qtap-sandbox.qpoint.io
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: qtap
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: qtap
spec:
  selector:
    app: qtap
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtap-deployment
  labels:
    app: qtap
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: qtap
  template:
    metadata:
      labels:
        app: qtap
    spec:
      containers:
      - name: qtap
        image: tylerflint/qtap:v3
        env:
        - name: TOKEN
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IlFVZlpxRXlsZHNMZ01jZ056aW40IiwiZGVzdGluYXRpb25JZCI6ImtpTkFjcW1hV1REQk9GcDJVbE9xIiwicm9sZSI6InF0YXAiLCJpYXQiOjE2OTA1ODI2OTIsImV4cCI6MTc3Njg5NjI5Mn0._Ma5L6YcSIAuxdvl_iuWPkw7umZ6ANFmfzFwPo6O3NM"
        - name: LISTEN
          value: "0.0.0.0:3333"
        ports:
        - containerPort: 3000

      # try to keep them on different nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
            - weight: 1  
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: NotIn 
                    values:
                    - qtap
                topologyKey: kubernetes.io/hostname